#!/usr/bin/env bash
# scripts/prereq-secrets.sh — create the K8s Secrets pi-kube needs and print the
# `helm install` command to run next.
#
# Stage plain files under ./prereq/ (gitignored), then run this script. It
# auto-detects whatever you staged and wires it in — no manual flags:
#
#   prereq/ssh_key.pub   SSH authorized key (key: authorized_keys) → Secret pi-ssh-keys
#   prereq/wg.conf       WireGuard client config   (key: wg0.conf) → Secret pi-wg
#   prereq/auth.json     pre-seeds ~/.pi/agent/auth.json (read-only) → Secret pi-auth
#   prereq/.env          KEY=VALUE lines → Secret pi-env (injected as pod env via envFrom)
#   prereq/my-values.yaml your values; auto-generated from what you staged if absent
#
# Exposure is auto-picked from what you staged:
#   wg.conf present        → wireguard   (needs ssh_key.pub too)
#   only ssh_key.pub        → loadbalancer
#   neither                 → none        (kubectl exec; no secrets needed)
#
# Usage:
#   scripts/prereq-secrets.sh [--namespace NS] [--release NAME] [--image-tag TAG]
#   -h, --help
#
# The chart resolves image.tag to its own version when empty, so you normally
# don't need --image-tag — pass it only to pin a specific build (e.g. a
# main-snapshot "<version>-<sha>" or the "-full" variant).

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PREREQ="$REPO_DIR/prereq"
EXAMPLE_VALUES="$REPO_DIR/examples/my-values.yaml"

namespace="pi-kube"
release="pi"
image_tag=""

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help) sed -n '3,/^$/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    --namespace)  namespace="${2:?--namespace needs a NS}";  shift 2 ;;
    --release)    release="${2:?--release needs a NAME}";     shift 2 ;;
    --image-tag)  image_tag="${2:?--image-tag needs a TAG}";  shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

command -v kubectl >/dev/null || { echo "Error: kubectl not found in PATH" >&2; exit 1; }
mkdir -p "$PREREQ"

# --- Detected prereq files ------------------------------------------------
ssh_key="$PREREQ/ssh_key.pub"
wg_conf="$PREREQ/wg.conf"
auth_json="$PREREQ/auth.json"
env_file="$PREREQ/.env"
values="$PREREQ/my-values.yaml"

# --- Resolve exposure from staged files -----------------------------------
# Exposure implied by what's currently staged (used to generate the values
# file, and to regenerate a stale auto-generated one).
if [ -f "$wg_conf" ] && [ -f "$ssh_key" ]; then
  staged_exposure="wireguard"
elif [ -f "$ssh_key" ]; then
  staged_exposure="loadbalancer"
else
  staged_exposure="none"
fi

# Decide whether to (re)generate prereq/my-values.yaml.
#  - no values file yet              → generate
#  - user-edited values file         → respect as-is (read exposure from it)
#  - auto-generated but out of sync with what's staged → regenerate, so the
#    Secrets we create below are actually wired into Helm. Without this, a
#    values file produced on a first run with nothing staged (exposure=none)
#    would stick at `none` even after you stage wg.conf/ssh_key.pub/auth.json,
#    and the printed `helm install` would spawn no sshd/wg sidecars — the
#    Secrets would exist but be ignored.
regen=false
if [ -f "$values" ]; then
  exposure=$(awk '/^ingress:/{f=1; next} f && /^[^[:space:]#]/{f=0} f && /^[[:space:]]*exposure:/{sub(/^[[:space:]]*exposure:[[:space:]]*/,""); sub(/[[:space:]]*#.*$/,""); print; exit}' "$values")
  exposure="${exposure:-none}"
  if grep -q '# Auto-generated by scripts/prereq-secrets.sh' "$values"; then
    if [ "$exposure" != "$staged_exposure" ]; then
      regen=true
    elif [ -f "$auth_json" ] && ! grep -q 'authJsonSecret: pi-auth' "$values"; then
      regen=true
    elif [ -f "$env_file" ] && ! grep -q 'existingSecret: pi-env' "$values"; then
      regen=true
    fi
  fi
else
  regen=true
fi

if [ "$regen" = true ]; then
  exposure="$staged_exposure"
  # Generate a minimal, commented values overlay wired to the staged secrets.
  {
    echo "# Auto-generated by scripts/prereq-secrets.sh from staged prereq/ files."
    echo "# Edit freely; delete it to regenerate from what's in prereq/."
    echo
    echo "ingress:"
    echo "  exposure: $exposure"
    if [ "$exposure" != "none" ]; then
      echo "  ssh:"
      echo "    enabled: true"
      echo "    port: 2222"
      echo "    authorizedKeysSecret: pi-ssh-keys"
    fi
    if [ "$exposure" = "wireguard" ]; then
      echo "  wireguard:"
      echo "    configSecret: pi-wg"
    fi
    if [ -f "$auth_json" ] || [ -f "$env_file" ]; then
      echo "credentials:"
      [ -f "$auth_json" ] && echo "  authJsonSecret: pi-auth   # read-only, blocks /login in the TUI"
      [ -f "$env_file" ]   && echo "  existingSecret: pi-env     # from prereq/.env (KEY=VALUE → pod env)"
    fi
  } > "$values"
  echo "==> wrote $values (exposure=$exposure)"
fi

# --- Validate required files per exposure ---------------------------------
require() { [ -f "$1" ] || { echo "Error: $2 not found: $1" >&2; exit 1; }; }
case "$exposure" in
  wireguard)    require "$ssh_key" "ssh_key.pub is required for wireguard"; require "$wg_conf" "wg.conf is required for wireguard" ;;
  loadbalancer) require "$ssh_key" "ssh_key.pub is required for loadbalancer" ;;
  none)         ;;
  tailscale|cloudflare) echo "Error: '$exposure' needs a Secret this script doesn't stage — see SETUP.md section 0c." >&2; exit 1 ;;
  *) echo "Error: unknown exposure '$exposure' in $values (none|loadbalancer|wireguard)" >&2; exit 1 ;;
esac

# --- Namespace (idempotent) -----------------------------------------------
echo "==> Namespace $namespace"
kubectl get namespace "$namespace" >/dev/null 2>&1 \
  || kubectl create namespace "$namespace"

# --- Secrets (idempotent) -------------------------------------------------
make_secret() {  # name key file — idempotent (create-or-update)
  echo "==> Secret $1 (from $3, key=$2)"
  kubectl -n "$namespace" create secret generic "$1" \
    --from-file="$2=$3" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
}

[ -f "$ssh_key" ]   && make_secret pi-ssh-keys authorized_keys "$ssh_key"
[ -f "$wg_conf" ]   && make_secret pi-wg       wg0.conf        "$wg_conf"
[ -f "$auth_json" ] && make_secret pi-auth     auth.json       "$auth_json"

# .env → Secret pi-env (one literal per KEY=VALUE line; blank/comment lines skipped).
if [ -f "$env_file" ]; then
  literal_args=()
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      ''|\#*) continue ;;
      *=*) literal_args+=("--from-literal=$line") ;;
      *)  echo "Error: bad line in $env_file (expected KEY=VALUE): $line" >&2; exit 1 ;;
    esac
  done < "$env_file"
  if [ ${#literal_args[@]} -gt 0 ]; then
    echo "==> Secret pi-env (from $env_file)"
    kubectl -n "$namespace" create secret generic pi-env "${literal_args[@]}" \
      --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  fi
fi

# --- Print the helm install command ---------------------------------------
# The chart resolves image.tag to its own version, so we only set it when an
# explicit override was given.
cmd="  helm install $release ./charts/pi -n $namespace -f $values"
[ -n "$image_tag" ] && cmd="$cmd \\
    --set image.tag=$image_tag"

echo
echo "Prereqs ready. Run:"
echo -e "$cmd"
echo
echo "Then wait for rollout:"
echo "  kubectl -n $namespace rollout status deploy/$release --timeout=180s"
case "$exposure" in
  loadbalancer) echo "  kubectl -n $namespace get svc ${release}-ssh    # ssh -p 2222 pi@<EXTERNAL-IP>" ;;
  wireguard)    echo "  ssh -p 2222 pi@<pod-tunnel-ip>                  # the Address from your wg.conf" ;;
  none)         echo "  kubectl -n $namespace exec -it deploy/$release -- pi" ;;
esac